[project]
name = "postgres-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "asyncpg>=0.30.0",
    "mcp[cli]>=1.9.1",
    "python-dotenv>=1.1.0",
]
